version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      pip-dependencies:
        patterns:
          - "*"  # Groups all dependencies
    target-branch: "develop"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha-dependencies:
        patterns:
          - "*"  # Groups all GitHub Actions
    target-branch: "develop"
