site_name: stitchee
site_description: Harmony service that concatenates netCDF4 data files along an existing dimension
site_url: https://github.com/nasa/stitchee

repo_name: nasa/stitchee
repo_url: https://github.com/nasa/stitchee
edit_uri: ""

theme:
  name: "material"
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - OVERVIEW:
      - "Readme": "index.md"
  - SAMBAH Service Chain:
      - "Description and known limitations": "sambah_readme.md"
  - EXAMPLES:
      - "Usage of STITCHEE via Harmony": "tutorial_examples.ipynb"

extra_css:
  - css/styles.css

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.details
  - meta
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: yes
            show_submodules: no
            show_root_heading: false
            show_source: false
          paths: [concatenator] # Adjust 'src' to your project's source directory if different
  - mkdocs-jupyter:
      execute: False
      ignore:
        - "**/.ipynb_checkpoints/*"

watch:
  - docs
  - concatenator
