name: Integration Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    secrets:
      DEK_EDL_USER:
        required: true
      DEK_EDL_PASSWORD:
        required: true
  push:
    branches:
      - main
      - develop
      - release/**
      - feature/**

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: integration-tests-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VERSION: "1.3.2"
  PYTHON_VERSION: "3.10"

jobs:
  run-integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install package
        run: poetry install --with=integration --without harmony

      - name: Test
        env:
          EDL_USER: ${{ secrets.DEK_EDL_USER }}
          EDL_PASSWORD: ${{ secrets.DEK_EDL_PASSWORD }}
        run: |
          scripts/create-netrc
          poetry run pytest --cov=concatenator --cov-report=term-missing --log-cli-level=INFO tests/integration -F integration

      - name: Upload coverage
        uses: codecov/codecov-action@v4
