name: Integration Tests

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true
      DEK_EDL_USER:
        required: true
      DEK_EDL_PASSWORD:
        required: true
  workflow_dispatch:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: integration-tests-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Retrieve repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --extra dev --extra integration --frozen

      - name: Test
        env:
          EDL_USER: ${{ secrets.DEK_EDL_USER }}
          EDL_PASSWORD: ${{ secrets.DEK_EDL_PASSWORD }}
        run: |
          scripts/create-netrc
          uv run pytest --cov=stitchee --cov-report=xml tests/integration

      - name: Upload coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          flags: integration
