name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - feature/**
      - issue/**
      - issues/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: 1.3.2

    - name: Install stitchee
      run: poetry install

    - name: Lint
      run: |
        poetry run ruff concatenator

    - name: Test with pytest
      run: |
        poetry run pytest tests/test_group_handling.py
      # TODO: expand tests to include full concatenation runs, i.e., don't just run test_group_handling.py
