# This workflow will install Python dependencies, run tests,
# and report test results and code coverage as artifacts. It will
# be called by the workflow that run tests against new PRs and as
# a first step in the workflow that publishes new Docker images.

name: A reusable workflow to build and run the unit test suite

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true
  workflow_dispatch:

env:
  POETRY_VERSION: "1.3.2"
  PYTHON_VERSION: "3.10"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install package
        run: poetry install

      - name: Run linting
        run: |
          poetry run ruff concatenator

      - name: Run tests and collect coverage
        run: poetry run pytest --cov=concatenator tests/unit/test_dataset_and_group_handling.py
        # TODO: expand tests to include full concatenation runs, i.e., not only test_dataset_and_group_handling.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
